name: Run test cases

on: [push, pull_request]

jobs:
  run_test_cases:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        influxdb_tag:
          - 2.5.0
    steps:
      - uses: actions/checkout@v4
      - name: run test cases
        env:
          INFLUXDB_TAG: ${{ matrix.influxdb_tag }}
        run: |
          docker compose -f ./docker-compose.yml up -d
          sleep 15
          docker exec -i erlang sh -c "make xref"
          docker exec -i erlang sh -c "make dialyzer"
          docker exec -i erlang sh -c "make eunit"
          docker exec -i erlang sh -c "make ct"
      - name: get container logs on failure
        if: failure()
        run: |
          echo "============== influxdb_tcp-begin =============="
          docker logs influxdb_tcp
          echo "============== influxdb_tcp-end =============="
